apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-service-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-service-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: GITHUB_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-service-production-config-secret
                   key: GITHUB_CALLBACK_URL
             - name: SECRET
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-service-production-config-secret
                   key: SECRET
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-service-production-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-service-production-config-secret
                   key: GOOGLE_CLIENT_SECRET
             - name: RECAPTCHA_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-service-production-config-secret
                   key: RECAPTCHA_SECRET_KEY
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: api-gateway-service-production-config-secret
                   key: DATABASE_URL
